version: '3.8'

services:
 opencv:
  build:
   context: .
  ports:
  - 2000:2000
  volumes:
  - ./:/app
  env_file:
  - .env
  deploy:
    restart_policy:
      condition: any
      delay: 5s
      window: 60s